# Generated by Django 5.1.5 on 2025-02-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainabilityAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
